name: Dynamiccheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: sudo apt-get install valgrind
    - name: Dynamic
      run: valgrind Calculator.out 3_Implementation

